import { StyleSheet } from 'react-native';
import {
    ACTIVE_RIDE_BUTTON_HEIGHT,
    ACTIVE_RIDE_BUTTON_WIDTH,
    CURRENT_LOC_FAB_RISE,
    SCREEN_HEIGHT,
} from './constants';

export const styles = 
StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFF' },
  loginScreen: { flex: 1, backgroundColor: '#FFFFFF', paddingHorizontal: 0 },
  loginHero: { backgroundColor: '#0B61FF', paddingTop: 56, paddingBottom: 32, paddingHorizontal: 24, alignItems: 'center' },
  loginBrandName: { fontSize: 42, fontWeight: '900', color: '#FFFFFF', marginBottom: 8 },
  loginBrandTagline: { fontSize: 16, fontWeight: '700', color: '#E6F0FF' },
  loginForm: { paddingHorizontal: 24, paddingTop: 32, paddingBottom: 24 },
  loginFormTitle: { fontSize: 26, fontWeight: '900', color: '#0B61FF', marginBottom: 6 },
  loginFormSubtitle: { fontSize: 14, color: '#475569', marginBottom: 24, lineHeight: 20 },
  loginInputWrap: { marginBottom: 18 },
  loginLabel: { fontSize: 12, fontWeight: '700', color: '#111827', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  loginInput: { backgroundColor: '#F9FAFB', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, color: '#111827' },
  loginPrimaryButton: { backgroundColor: '#0B61FF', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 8, marginBottom: 12 },
  loginPrimaryButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },

  validationModalWrap: { flex: 1, backgroundColor: 'rgba(6,8,23,0.6)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  validationModalCard: { width: '100%', maxWidth: 420, backgroundColor: '#FFFFFF', borderRadius: 16, padding: 20, alignItems: 'center' },
  validationModalTitle: { fontSize: 18, fontWeight: '900', color: '#0F172A', marginBottom: 8, textAlign: 'center' },
  validationModalMessage: { color: '#374151', fontSize: 14, textAlign: 'center', marginBottom: 18 },
  validationModalButton: { backgroundColor: '#0F172A', paddingVertical: 12, paddingHorizontal: 28, borderRadius: 12 },
  validationModalButtonText: { color: '#FFFFFF', fontWeight: '800' },
  loginSecondaryButton: { borderWidth: 1, borderColor: '#0B61FF', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  loginSecondaryButtonText: { color: '#0B61FF', fontSize: 16, fontWeight: '700' },
  loginHintText: { fontSize: 13, color: '#6B7280', marginBottom: 20, marginTop: 4, lineHeight: 18 },
  loginFooter: { position: 'absolute', bottom: 32, left: 24, right: 24, textAlign: 'center', fontSize: 12, color: '#9CA3AF', fontWeight: '600' },
  authLoadingScreen: { flex: 1, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', padding: 24 },
  authLoadingTitle: { color: '#0B61FF', fontSize: 38, fontWeight: '900', marginBottom: 8 },
  authLoadingText: { color: '#475569', fontSize: 14, fontWeight: '700' },
  map: { flex: 1 },
  loyaltyBackground: { flex: 1, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', padding: 30 },
  loyaltyIcon: { fontSize: 80, marginBottom: 20 },
  loyaltyTitle: { fontSize: 22, fontWeight: '900', color: '#1C1C1E', marginBottom: 20, textAlign: 'center' },
  loyaltyCard: { backgroundColor: '#F8F9FB', padding: 20, borderRadius: 20, width: '100%', marginBottom: 30 },
  loyaltyText: { fontSize: 16, color: '#3A3A3C', marginBottom: 15, lineHeight: 22 },
  loyaltySlogan: { fontSize: 14, color: '#007AFF', fontWeight: 'bold' },
  proBackground: { flex: 1, backgroundColor: '#F8F9FB' },
  brandingContainer: { padding: 30, alignItems: 'center', width: '100%' },
  brandName: { fontSize: 42, fontWeight: '900', color: '#007AFF', marginBottom: 10 },
  slogan: { fontSize: 18, fontWeight: '700', color: '#1C1C1E', textAlign: 'center', marginBottom: 20 },
  dashboard: { flexDirection: 'row', flexWrap: 'wrap', backgroundColor: 'white', padding: 20, borderRadius: 25, elevation: 4, width: '100%', justifyContent:'space-between' },
  historyBtn: {
    marginTop: 12,
    backgroundColor: '#0F172A',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 18,
    width: '100%',
    borderWidth: 1,
    borderColor: '#1E293B',
    shadowColor: '#0F172A',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  historyBtnEyebrow: { color: '#94A3B8', fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 4 },
  historyBtnText: { color: 'white', fontWeight: '700' },
  historyBtnSubtext: { color: '#CBD5E1', fontSize: 12, lineHeight: 18, marginTop: 4 },
  changeVehicleBtn: { marginTop: 10, backgroundColor: '#1D4ED8', paddingVertical: 10, paddingHorizontal: 16, borderRadius: 12 },
  changeVehicleBtnText: { color: '#FFFFFF', fontWeight: '700' },
  dashItem: { width: '45%', alignItems: 'center', marginBottom: 15 },
  dashVal: { fontSize: 22, fontWeight: '900', color: '#1C1C1E' },
  dashLab: { fontSize: 12, color: '#8E8E93', fontWeight: 'bold' },
  driverInfoCard: { width: '100%', backgroundColor: '#FFFFFF', borderRadius: 14, borderWidth: 1, borderColor: '#E5E7EB', padding: 12, marginTop: 10 },
  driverInfoTitle: { fontSize: 14, fontWeight: '900', color: '#111827', marginBottom: 6 },
  driverInfoText: { fontSize: 13, color: '#374151', marginBottom: 3 },
  driverLockedPhoneCard: { backgroundColor: '#EEF6FF', borderWidth: 1, borderColor: '#BFDBFE', borderRadius: 12, padding: 12, marginBottom: 10 },
  driverLockedPhoneLabel: { color: '#1D4ED8', fontSize: 11, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 4 },
  driverLockedPhoneValue: { color: '#0F172A', fontSize: 18, fontWeight: '900', marginBottom: 4 },
  driverLockedPhoneHint: { color: '#475569', fontSize: 12, lineHeight: 17 },
  driverAvailabilityCard: { width: '100%', backgroundColor: '#F8FAFC', borderColor: '#CBD5E1', borderWidth: 1, borderRadius: 12, padding: 10, marginTop: 10, marginBottom: 4, flexDirection: 'row', alignItems: 'center', gap: 10 },
  driverAvailabilityTitle: { color: '#0F172A', fontWeight: '800' },
  driverAvailabilityHint: { color: '#475569', fontSize: 12, marginTop: 2 },
  header: { position: 'absolute', top: 50, left: 20, right: 20, flexDirection: 'row', justifyContent: 'space-between', zIndex: 10 },
  currentLocFab: { position: 'absolute', right: 18, bottom: 235 + CURRENT_LOC_FAB_RISE, width: 24, height: 24, borderRadius: 12, backgroundColor: '#007AFF', alignItems: 'center', justifyContent: 'center', elevation: 8, shadowColor: '#111827', shadowOpacity: 0.2, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, zIndex: 12, borderWidth: 1, borderColor: '#005FCC' },
  currentLocFabText: { fontSize: 12, color: '#FFFFFF', fontWeight: '900' },
  activeRideButton: { position: 'absolute', width: ACTIVE_RIDE_BUTTON_WIDTH, height: ACTIVE_RIDE_BUTTON_HEIGHT, backgroundColor: '#0E7490', borderRadius: 26, elevation: 12, shadowColor: '#0F172A', shadowOpacity: 0.28, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, zIndex: 12, alignItems: 'center', justifyContent: 'center' },
  activeRideButtonPressable: { flex: 1, width: '100%', alignItems: 'center', justifyContent: 'center' },
  activeRideButtonText: { color: '#FFFFFF', fontWeight: '800', letterSpacing: 0.2 },
  badge: { backgroundColor: 'white', padding: 12, borderRadius: 25, elevation: 5 },
  logout: { backgroundColor: '#FF3B30', width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  bottomCard: { position: 'absolute', bottom: 0, width: '100%', backgroundColor: 'white', padding: 20, borderTopLeftRadius: 30, borderTopRightRadius: 30, elevation: 20, maxHeight: '100%' },
  bottomCardOverlay: { top: 56, bottom: 0, left: 0, right: 0, width: '100%', borderTopLeftRadius: 0, borderTopRightRadius: 0, paddingTop: 12, zIndex: 25, elevation: 30 },
  passengerCardHandleWrap: { alignItems: 'center', marginBottom: 10, marginTop: -8 },
  passengerCardHandle: { width: 54, height: 6, borderRadius: 4, backgroundColor: '#CBD5E1', marginBottom: 6 },
  passengerCardHandleHint: { fontSize: 11, color: '#64748B', fontWeight: '600' },
  passengerExpandedPage: { maxHeight: SCREEN_HEIGHT - 56 },
  passengerExpandedPageContent: { paddingBottom: 24 },
  passengerExpandedHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 2 },
  passengerExpandedTitle: { fontSize: 18, fontWeight: '900', color: '#0F172A', marginBottom: 3 },
  passengerExpandedSubTitle: { fontSize: 12, color: '#475569', marginBottom: 10, lineHeight: 18 },
  passengerExpandedBackBtn: { backgroundColor: '#E0E7FF', borderWidth: 1, borderColor: '#A5B4FC', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999 },
  passengerExpandedBackBtnText: { color: '#3730A3', fontWeight: '800', fontSize: 12 },
  passengerExpandedBottomBackBtn: { marginTop: 10, backgroundColor: '#111827', borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  passengerExpandedBottomBackBtnText: { color: '#FFFFFF', fontWeight: '800' },
  input: { backgroundColor: '#F2F2F7', padding: 12, borderRadius: 12, marginBottom: 10 },
  primaryButton: { backgroundColor: '#007AFF', padding: 16, borderRadius: 15, alignItems: 'center' },
  verificationModal: { flex: 1, backgroundColor: '#0B1020' },
  subscriptionModal: { flex: 1, backgroundColor: '#07111F' },
  subscriptionScroll: { paddingHorizontal: 24, paddingTop: 72, paddingBottom: 36 },
  subscriptionHero: { marginBottom: 18 },
  subscriptionBadge: { alignSelf: 'flex-start', backgroundColor: 'rgba(255,255,255,0.08)', color: '#DCE7FF', borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, fontWeight: '800', marginBottom: 14, letterSpacing: 0.4 },
  subscriptionTitle: { color: '#FFFFFF', fontSize: 30, fontWeight: '900', lineHeight: 36, marginBottom: 10 },
  subscriptionSubtitle: { color: '#C9D5F2', fontSize: 15, lineHeight: 22 },
  subscriptionPriceCard: { backgroundColor: '#0F1A31', borderRadius: 24, padding: 20, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', marginBottom: 14 },
  subscriptionPriceLabel: { color: '#9DB0DB', textTransform: 'uppercase', letterSpacing: 1, fontSize: 11, fontWeight: '700', marginBottom: 4 },
  subscriptionPriceValue: { color: '#FFFFFF', fontSize: 40, fontWeight: '900', lineHeight: 44 },
  subscriptionPriceMeta: { color: '#B8C6E6', fontSize: 13, marginTop: 6 },
  subscriptionFeatureCard: { backgroundColor: '#F7F9FF', borderRadius: 24, padding: 18, marginBottom: 14, borderWidth: 1, borderColor: '#DEE6FF' },
  subscriptionFeatureTitle: { color: '#0F172A', fontSize: 17, fontWeight: '900', marginBottom: 10 },
  subscriptionFeatureLine: { color: '#334155', fontSize: 14, lineHeight: 21, marginBottom: 6 },
  subscriptionNoticeCard: { backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 18, padding: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', marginBottom: 14 },
  subscriptionNoticeTitle: { color: '#DCE7FF', fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 4 },
  subscriptionNoticeText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  subscriptionErrorCard: { backgroundColor: 'rgba(239,68,68,0.12)', borderRadius: 16, padding: 12, borderWidth: 1, borderColor: 'rgba(239,68,68,0.28)', marginBottom: 14 },
  subscriptionErrorText: { color: '#FCA5A5', fontSize: 13, lineHeight: 18 },
  subscriptionPayButton: { backgroundColor: '#FFFFFF', borderRadius: 18, paddingVertical: 16, alignItems: 'center', marginTop: 4 },
  subscriptionPayButtonText: { color: '#08111F', fontSize: 16, fontWeight: '900' },
  subscriptionFootnote: { color: '#9DB0DB', fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 14 },
  checkoutModalWrap: { flex: 1, backgroundColor: '#07111F', paddingTop: 54, paddingHorizontal: 16, paddingBottom: 16 },
  checkoutHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 12 },
  checkoutTitle: { color: '#FFFFFF', fontSize: 24, fontWeight: '900', marginBottom: 4 },
  checkoutSubtitle: { color: '#C9D5F2', fontSize: 13, lineHeight: 18 },
  checkoutClose: { color: '#B7C7FF', fontSize: 15, fontWeight: '800', paddingHorizontal: 8, paddingVertical: 6 },
  checkoutWebviewShell: { flex: 1, borderRadius: 24, overflow: 'hidden', backgroundColor: '#FFFFFF' },
  checkoutWebview: { flex: 1, backgroundColor: '#FFFFFF' },
  pendingReviewPage: { flex: 1, paddingHorizontal: 22, paddingTop: 34, paddingBottom: 24, justifyContent: 'center' },
  pendingReviewBadgeRow: { marginBottom: 14 },
  pendingReviewBadge: { alignSelf: 'flex-start', backgroundColor: 'rgba(139, 164, 255, 0.16)', color: '#B7C7FF', borderWidth: 1, borderColor: 'rgba(139, 164, 255, 0.28)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, fontWeight: '800', letterSpacing: 0.8, textTransform: 'uppercase' },
  pendingReviewTitle: { color: '#FFFFFF', fontSize: 30, fontWeight: '900', lineHeight: 36, marginBottom: 12 },
  pendingReviewText: { color: '#D4DAF0', fontSize: 15, lineHeight: 22, marginBottom: 18 },
  pendingReviewCard: { backgroundColor: '#121A33', borderRadius: 24, padding: 18, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', marginBottom: 14 },
  pendingReviewCardTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '800', marginBottom: 10 },
  pendingReviewCardText: { color: '#C7D1ED', fontSize: 14, lineHeight: 20, marginBottom: 6 },
  pendingReviewFooter: { backgroundColor: 'rgba(255,255,255,0.04)', borderRadius: 18, padding: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.06)' },
  pendingReviewFooterText: { color: '#9DB0DB', fontSize: 12, lineHeight: 18, textAlign: 'center' },
  pendingWrap: { flex: 1, paddingHorizontal: 24, paddingTop: 72, backgroundColor: '#0B1020' },
  pendingBadge: { alignSelf: 'flex-start', backgroundColor: 'rgba(139, 164, 255, 0.18)', color: '#B7C7FF', borderWidth: 1, borderColor: 'rgba(139, 164, 255, 0.28)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, fontWeight: '800', marginBottom: 14 },
  pendingTitle: { color: '#FFFFFF', fontSize: 28, fontWeight: '900', lineHeight: 34, marginBottom: 12 },
  pendingText: { color: '#D4DAF0', fontSize: 15, lineHeight: 22, marginBottom: 18 },
  pendingCard: { backgroundColor: '#121A33', borderRadius: 22, padding: 18, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  pendingCardTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '800', marginBottom: 6 },
  pendingCardText: { color: '#C7D1ED', fontSize: 14, lineHeight: 20 },
  pendingBack: { position: 'absolute', top: 18, left: 18, padding: 8 },
  pendingBackText: { color: '#FFFFFF', fontWeight: '700' },
  currentLocationHintText: { marginTop: 6, fontSize: 11, color: '#6B7280', textAlign: 'center' },
  searchSuggestionPanel: { backgroundColor: '#F8FAFA', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 16, padding: 8, marginBottom: 10, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  searchSuggestionItem: { paddingVertical: 12, paddingHorizontal: 14, borderRadius: 14, backgroundColor: '#FFFFFF', marginBottom: 8, borderWidth: 1, borderColor: '#E5E7EB' },
  searchSuggestionText: { color: '#0F172A', fontSize: 14, fontWeight: '700' },
  cancelButton: { backgroundColor: '#FF3B30', padding: 12, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  buttonText: { color: 'white', fontWeight: 'bold' },
  rideCard: { width: 85, padding: 10, backgroundColor: '#fff', marginRight: 10, borderRadius: 15, alignItems: 'center', borderWidth: 1, borderColor: '#E5E5EA' },
  rideChoiceGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 10 },
  rideSelectCard: { width: '31%', padding: 10, backgroundColor: '#fff', marginBottom: 10, borderRadius: 15, alignItems: 'center', borderWidth: 1, borderColor: '#E5E5EA' },
  shareRideCard: { borderColor: '#D9A600', backgroundColor: '#FFF1B8', borderWidth: 2, shadowColor: '#B88900', shadowOpacity: 0.24, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 5 },
  parcelRideCard: { borderColor: '#1B5E20', backgroundColor: '#EAF8EE', borderWidth: 2, shadowColor: '#1B5E20', shadowOpacity: 0.16, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  earnRideCard: { borderColor: '#B45309', backgroundColor: '#FFF3D6', borderWidth: 2, shadowColor: '#B45309', shadowOpacity: 0.18, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  shareAttractLabel: { position: 'absolute', top: -8, backgroundColor: '#E8B400', color: '#3F2C00', fontSize: 9, fontWeight: '900', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8, overflow: 'hidden', borderWidth: 1, borderColor: '#9A7400' },
  parcelAttractLabel: { position: 'absolute', top: -8, backgroundColor: '#1B5E20', color: '#FFFFFF', fontSize: 9, fontWeight: '900', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8, overflow: 'hidden', borderWidth: 1, borderColor: '#0E3B13' },
  earnAttractLabel: { position: 'absolute', top: -8, backgroundColor: '#B45309', color: '#FFFFFF', fontSize: 9, fontWeight: '900', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8, overflow: 'hidden', borderWidth: 1, borderColor: '#7C2D12' },
  parcelCardHint: { marginTop: 4, color: '#1B5E20', fontSize: 10, fontWeight: '700', textAlign: 'center' },
  earnCardHint: { marginTop: 4, color: '#9A3412', fontSize: 10, fontWeight: '700', textAlign: 'center' },
  selected: { borderColor: '#007AFF', backgroundColor: '#F2F7FF', borderWidth: 2 },
  searchingText: { fontSize: 14, fontWeight: '700', color: '#007AFF', textAlign: 'center' },
  highlightPrice: { fontSize: 20, fontWeight: '900', color: '#34C759' },
  routeText: { fontSize: 14, fontWeight: '700', color: '#1C1C1E', marginTop: 2 },
  otpClearBox: { backgroundColor: '#F2F7FF', padding: 15, borderRadius: 15, borderWidth: 1, borderColor: '#007AFF', alignItems: 'center', width: '100%' },
  otpValue: { fontSize: 32, fontWeight: '900' },
  otpLabel: { fontSize: 10, color: '#007AFF', fontWeight: 'bold' },
  detailsBtn: { backgroundColor: '#F2F2F7', padding: 12, borderRadius: 12, width: '100%', alignItems: 'center', marginTop: 10 },
  detailsBtnText: { fontWeight: '700' },
  chatButton: { backgroundColor: '#127A40', padding: 12, borderRadius: 12, width: '100%', alignItems: 'center', marginTop: 10, position: 'relative' },
  chatButtonText: { color: 'white', fontWeight: '700' },
  unreadDot: { position: 'absolute', right: 12, top: 8, width: 10, height: 10, borderRadius: 5, backgroundColor: '#D62828' },
  callBtn: { marginTop: 8, backgroundColor: '#E8F5E9', borderWidth: 1, borderColor: '#1B5E20', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 14 },
  callBtnText: { color: '#1B5E20', fontWeight: '700' },
  smallCallBtn: { backgroundColor: '#E8F5E9', borderColor: '#1B5E20', borderWidth: 1, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, marginLeft: 6 },
  smallCallBtnText: { color: '#1B5E20', fontWeight: '700', fontSize: 12 },
  smallNavBtn: { backgroundColor: '#111827', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, marginLeft: 6 },
  smallNavBtnText: { color: 'white', fontWeight: '700', fontSize: 12 },
  reachingBtn: { backgroundColor: '#FFF4CC', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, marginLeft: 6, borderColor: '#E1B500', borderWidth: 1 },
  reachingBtnText: { color: '#6B4E00', fontWeight: '800', fontSize: 12 },
  contactCard: { backgroundColor: '#F4FBF6', borderColor: '#CFE8D5', borderWidth: 1, borderRadius: 12, padding: 10, marginBottom: 10 },
  contactTitle: { fontWeight: '800', marginBottom: 4, color: '#1B5E20' },
  contactText: { color: '#1F2937' },
  sharePassengerRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
  logoutMenu: { position: 'absolute', top: 45, right: 0, backgroundColor: 'white', borderRadius: 8, elevation: 10, shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, minWidth: 150 },
  logoutMenuItem: { padding: 12, borderBottomWidth: 1, borderBottomColor: '#E5E5EA' },
  logoutMenuText: { fontSize: 14, fontWeight: '600', color: '#FF3B30' },
  menuItemText: { fontSize: 14, fontWeight: '600', color: '#111827' },
  journeyQuoteCard: { position: 'absolute', left: 16, right: 16, bottom: 24, backgroundColor: 'rgba(255,255,255,0.96)', borderRadius: 18, padding: 14, borderWidth: 1, borderColor: '#D1D5DB', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 10, shadowOffset: { width: 0, height: 2 }, elevation: 4 },
  journeyQuoteText: { fontSize: 16, fontWeight: '800', color: '#111827', textAlign: 'center' },
  sharePassengerMeta: { color: '#4B5563', fontSize: 12 },
  shareDriverFlowCard: { backgroundColor: '#FFF6CC', borderColor: '#E8C549', borderWidth: 1, borderRadius: 14, padding: 10, marginBottom: 10, width: '100%' },
  shareDriverFlowTitle: { color: '#6B4E00', fontWeight: '900', fontSize: 15, marginBottom: 2 },
  shareDriverFlowSub: { color: '#7A5C00', fontWeight: '700', marginBottom: 8 },
  shareDriverTaskCard: { width: 170, backgroundColor: '#FFF0A6', borderColor: '#D8B03D', borderWidth: 1, borderRadius: 12, padding: 10, marginRight: 8 },
  shareDriverTaskCardSelected: { backgroundColor: '#FFD84D', borderColor: '#9F7600' },
  shareDriverTaskTitle: { color: '#4B3B00', fontWeight: '900', marginBottom: 4 },
  shareDriverTaskMeta: { color: '#6B5A14', fontSize: 12, marginBottom: 2 },
  shareDriverActionCard: { backgroundColor: '#FFFBE8', borderColor: '#E8C549', borderWidth: 1, borderRadius: 12, padding: 10 },
  shareSingleNotifCard: {
    backgroundColor: '#FFF0A8',
    borderColor: '#C99C18',
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 10,
    marginTop: 6,
    shadowColor: '#7A5C00',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  shareSingleNotifTitle: { color: '#5E4300', fontWeight: '900', marginBottom: 3 },
  shareSingleNotifMeta: { color: '#6B5A14', fontSize: 12 },
  parcelSingleNotifCard: { backgroundColor: '#EAF8EE', borderColor: '#8BC59B', borderWidth: 1, borderRadius: 10, padding: 8, marginTop: 6 },
  parcelSingleNotifTitle: { color: '#1B5E20', fontWeight: '900', marginBottom: 3 },
  parcelSingleNotifMeta: { color: '#256B31', fontSize: 12 },
  driverFilterCard: { backgroundColor: '#F8FAFC', borderColor: '#CBD5E1', borderWidth: 1, borderRadius: 12, padding: 10, marginTop: 10, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 10 },
  driverFilterTitle: { color: '#0F172A', fontWeight: '800' },
  driverFilterHint: { color: '#475569', fontSize: 12, marginTop: 2 },
  driverPromoFooter: { width: '100%', backgroundColor: '#FFFFFF', borderRadius: 18, padding: 14, marginTop: 12, alignItems: 'center', overflow: 'hidden', borderWidth: 1, borderColor: '#E5E7EB' },
  driverPromoPulse: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: '#007AFF', borderRadius: 18 },
  driverPromoTitle: { fontSize: 16, fontWeight: '800', color: '#0F172A', marginBottom: 4 },
  driverPromoText: { fontSize: 13, color: '#475569', textAlign: 'center', lineHeight: 18 },
  driverNotificationsScroll: { maxHeight: 330 },
  goHomeWrap: { backgroundColor: '#F0FDF4', borderWidth: 1, borderColor: '#BBF7D0', borderRadius: 12, padding: 10, marginBottom: 10 },
  goHomeButton: { backgroundColor: '#0F8A47', borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  goHomeButtonText: { color: '#FFFFFF', fontWeight: '800', fontSize: 15 },
  goHomeHintText: { color: '#166534', marginTop: 8, fontWeight: '600' },
  goHomeQuickHint: { marginTop: 6, color: '#166534', fontSize: 12, fontWeight: '700' },
  passengerFeatureCard: { marginTop: 10, backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#C7D2FE', borderRadius: 12, padding: 10 },
  passengerFeatureTitle: { color: '#3730A3', fontWeight: '900', marginBottom: 6 },
  passengerFeatureLine: { color: '#312E81', fontSize: 12, lineHeight: 18, marginBottom: 4 },
  passengerFeatureGrid: { gap: 8 },
  passengerFeatureTile: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#FFFFFF', borderRadius: 10, borderWidth: 1, borderColor: '#C7D2FE', padding: 8 },
  passengerFeatureTileIcon: { fontSize: 18 },
  passengerFeatureTileTitle: { color: '#312E81', fontWeight: '800', fontSize: 13 },
  passengerFeatureTileText: { color: '#4338CA', fontSize: 11, marginTop: 1 },
  notificationCard: { backgroundColor: '#fff', borderRadius: 15, padding: 15, marginBottom: 12, borderWidth: 1, borderColor: '#007AFF' },
  notifHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  accButton: { flex: 2, backgroundColor: '#34C759', padding: 12, borderRadius: 10, alignItems: 'center' },
  accText: { color: 'white', fontWeight: 'bold' },
  negButton: { flex: 1, backgroundColor: '#F2F2F7', padding: 12, borderRadius: 10, alignItems: 'center', marginRight: 10 },
  navButton: { backgroundColor: '#000', padding: 14, borderRadius: 12, marginBottom: 10, alignItems: 'center', width: '100%' },
  navButtonText: { color: 'white', fontWeight: 'bold' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  detailsModal: { backgroundColor: 'white', padding: 25, borderRadius: 25, width: '90%' },
  modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 15, textAlign:'center' },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  detailLabel: { color: '#8E8E93' },
  valText: { flex: 1, textAlign: 'right', fontWeight: '600' },
  loginContainer: { flex: 1, justifyContent: 'center', padding: 30 },
  title: { fontSize: 28, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
  switchAuth: { textAlign: 'center', marginTop: 20, color: '#007AFF' },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'center' },
  emptyText: { textAlign: 'center', color: '#8E8E93', marginVertical: 20 },
  driverNameText: { fontSize: 18, fontWeight: 'bold' },
  driverArrivingCard: { width: '100%', alignItems: 'center' },
  tipOption: { backgroundColor: '#E8F2FF', padding: 12, borderRadius: 10, width: '45%', alignItems: 'center', marginBottom: 5 },
  tipText: { color: '#007AFF', fontWeight: 'bold' },
  warningBox: { backgroundColor: '#FFFBE6', borderLeftWidth: 5, borderColor: '#FAAD14', padding: 15, borderRadius: 10, marginBottom: 20, width: '100%' },
  warningTitle: { fontWeight: '900', color: '#FAAD14', marginBottom: 5 },
  warningDesc: { fontSize: 13, color: '#595959' },
  suspensionOverlay: { backgroundColor: 'white', padding: 30, borderRadius: 20, alignItems: 'center', marginTop: 20, width: '90%', elevation: 10 },
  suspensionEmoji: { fontSize: 60, marginBottom: 10 },
  suspensionTitle: { fontSize: 22, fontWeight: '900', color: '#FF3B30', textAlign: 'center' },
  suspensionText: { textAlign: 'center', color: '#3A3A3C', marginVertical: 15 },
  crewBox: { backgroundColor: '#F2F2F7', padding: 15, borderRadius: 15, width: '100%', borderStyle: 'dashed', borderWidth: 2, borderColor: '#8E8E93' },
  crewLabel: { fontSize: 10, fontWeight: '900', color: '#8E8E93', textAlign: 'center', marginBottom: 5 },
  crewInput: { backgroundColor: 'white', padding: 10, borderRadius: 10, textAlign: 'center', marginBottom: 10 },
  crewBtn: { backgroundColor: '#1C1C1E', padding: 12, borderRadius: 10, alignItems: 'center' },
  cancelTitle: { fontWeight: 'bold', color: '#FF3B30', marginBottom: 10 },
  reasonBtn: { backgroundColor: '#F2F2F7', padding: 12, borderRadius: 10, marginBottom: 5 },
  historyCard: { backgroundColor: '#F8F9FB', borderRadius: 12, padding: 10, marginBottom: 8 },
  historyRoute: { fontWeight: '700', color: '#111827' },
  historyMeta: { marginTop: 2, color: '#374151' },
  shareMatchText: { marginTop: 4, color: '#7A5C00', fontWeight: '700', fontSize: 12 },
  shareNotifLine: { color: '#374151', fontSize: 12, marginTop: 2 },
  etaCard: { marginTop: 10, width: '100%', backgroundColor: '#FFF8D6', borderColor: '#E7C956', borderWidth: 1, borderRadius: 12, padding: 10, alignItems: 'center' },
  etaAuto: { fontSize: 24, marginBottom: 4 },
  etaText: { color: '#6B4E00', fontWeight: '700' },
  chatWrap: { flex: 1, backgroundColor: '#EAF8EE' },
  chatHeader: { paddingTop: 56, paddingBottom: 16, paddingHorizontal: 16, backgroundColor: '#0F8A47', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  chatTitle: { color: 'white', fontSize: 20, fontWeight: '800' },
  chatClose: { color: 'white', fontWeight: '700' },
  chatTargetsRow: { maxHeight: 50, backgroundColor: '#F7FCF8', borderBottomWidth: 1, borderBottomColor: '#D5EBDD', paddingHorizontal: 8, paddingVertical: 8 },
  chatTargetBtn: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999, backgroundColor: '#EAF5EE', marginRight: 8 },
  chatTargetBtnActive: { backgroundColor: '#0F8A47' },
  chatTargetText: { color: '#0F8A47', fontWeight: '700' },
  chatTargetTextActive: { color: 'white' },
  chatBubble: { maxWidth: '80%', borderRadius: 12, padding: 10, marginBottom: 8 },
  chatMine: { alignSelf: 'flex-end', backgroundColor: '#CFF2D6' },
  chatTheirs: { alignSelf: 'flex-start', backgroundColor: 'white' },
  chatName: { fontSize: 11, color: '#0F8A47', marginBottom: 2, fontWeight: '700' },
  chatText: { color: '#111827' },
  chatTargetTag: { marginTop: 4, fontSize: 11, color: '#7A5C00', fontWeight: '700' },
  chatComposer: { flexDirection: 'row', alignItems: 'center', padding: 10, backgroundColor: 'white', borderTopWidth: 1, borderTopColor: '#D1D5DB' },
  chatInput: { flex: 1, backgroundColor: '#F3F4F6', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 10, marginRight: 8 },
  chatSend: { backgroundColor: '#0F8A47', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 18 }
  ,driverMapModalWrap: { flex: 1, backgroundColor: '#FFFFFF' },
  driverMapModalMap: { flex: 1 },
  driverMapModalControls: { backgroundColor: 'rgba(255,255,255,0.96)', paddingHorizontal: 14, paddingTop: 12, paddingBottom: 20, borderTopWidth: 1, borderTopColor: '#D1D5DB' },
  driverMapModalTitle: { fontSize: 16, fontWeight: '900', color: '#0F172A', marginBottom: 4 },
  driverMapModalHint: { color: '#475569', marginBottom: 10 },
  disabledConfirmBtn: { backgroundColor: '#86EFAC', opacity: 0.45 }
  ,yellowTermsCard: { backgroundColor: '#FFF6CC', borderWidth: 1, borderColor: '#E8C549', borderRadius: 14, padding: 12, marginBottom: 14 },
  termsHeading: { color: '#6B4E00', fontWeight: '900', marginBottom: 8 },
  termsPoint: { color: '#5B4A17', marginBottom: 5, lineHeight: 18 },
  parcelTermsCard: { backgroundColor: '#EAF8EE', borderWidth: 1, borderColor: '#9AD7B0', borderRadius: 14, padding: 12, marginBottom: 14 },
  parcelTermsHeading: { color: '#1B5E20', fontWeight: '900', marginBottom: 8 }
  ,earnPageWrap: { flex: 1, backgroundColor: '#F8FAFC' },
  earnPageHeader: { paddingTop: 54, paddingHorizontal: 16, paddingBottom: 14, backgroundColor: 'white', borderBottomWidth: 1, borderBottomColor: '#E5E7EB', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  earnPageBack: { color: '#007AFF', fontWeight: '700' },
  earnPageTitle: { fontSize: 20, fontWeight: '900', color: '#111827' },
  earnPageContent: { padding: 16, paddingBottom: 120 },
  earnSummaryCard: { backgroundColor: '#FFF3D6', borderWidth: 1, borderColor: '#F59E0B', borderRadius: 14, padding: 14, marginBottom: 14 },
  earnSummaryLabel: { color: '#92400E', fontWeight: '700' },
  earnSummaryValue: { color: '#B45309', fontWeight: '900', fontSize: 28, marginTop: 4 },
  earnSummaryHint: { color: '#7C2D12', marginTop: 6, lineHeight: 18 },
  earnSectionTitle: { fontSize: 16, fontWeight: '800', color: '#111827', marginTop: 8, marginBottom: 8 },
  earnFooter: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 16, backgroundColor: 'white', borderTopWidth: 1, borderTopColor: '#E5E7EB' },
  earnWithdrawCard: { backgroundColor: '#0F172A', borderRadius: 18, padding: 16, marginBottom: 14, borderWidth: 1, borderColor: '#1E293B' },
  earnWithdrawTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 10 },
  earnWithdrawEyebrow: { color: '#93C5FD', fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 4 },
  earnWithdrawTitle: { color: '#FFFFFF', fontSize: 22, fontWeight: '900' },
  earnWithdrawBadge: { backgroundColor: '#ECFDF5', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  earnWithdrawBadgeText: { color: '#047857', fontWeight: '900', fontSize: 12 },
  earnWithdrawText: { color: '#CBD5E1', fontSize: 13, lineHeight: 19, marginBottom: 12 },
  earnWithdrawInput: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 12, marginBottom: 10, color: '#111827' },
  earnMoneyButton: { backgroundColor: '#22C55E', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginBottom: 10 },
  earnMoneyButtonText: { color: '#052E16', fontWeight: '900', fontSize: 15 },
  earnEmergencyButton: { backgroundColor: '#FEF3C7', borderRadius: 12, paddingVertical: 12, paddingHorizontal: 12, alignItems: 'center', borderWidth: 1, borderColor: '#F59E0B' },
  earnEmergencyButtonText: { color: '#92400E', fontWeight: '900', textAlign: 'center', fontSize: 13 },
  earnTermsCard: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#E5E7EB', marginBottom: 14 },
  earnTermsTitle: { color: '#111827', fontSize: 16, fontWeight: '900', marginBottom: 10 },
  earnTermsPoint: { color: '#374151', fontSize: 13, lineHeight: 20, marginBottom: 6 }
  ,shareAutoScreen: { flex: 1, backgroundColor: '#FFF6CC', alignItems: 'center', justifyContent: 'center', padding: 24 },
  shareAutoTopGlow: { position: 'absolute', top: -60, width: 220, height: 220, borderRadius: 110, backgroundColor: 'rgba(255, 220, 77, 0.35)' },
  shareAutoBadge: { backgroundColor: '#FFF0A6', color: '#7A5C00', fontWeight: '800', paddingVertical: 6, paddingHorizontal: 14, borderRadius: 999, marginBottom: 18, overflow: 'hidden' },
  shareAutoOrb: { width: 150, height: 150, borderRadius: 75, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center', elevation: 6, shadowColor: '#B38F00', shadowOpacity: 0.15, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, marginBottom: 22 },
  shareAutoOrbIcon: { fontSize: 56 },
  shareAutoTitle: { fontSize: 24, fontWeight: '900', color: '#4B3B00', textAlign: 'center', marginBottom: 10 },
  shareAutoSubtitle: { fontSize: 15, color: '#6B5A14', textAlign: 'center', lineHeight: 22, marginBottom: 18 },
  shareAutoTimerCard: { width: '100%', backgroundColor: 'rgba(255,255,255,0.72)', borderRadius: 22, padding: 18, alignItems: 'center', marginBottom: 16, borderWidth: 1, borderColor: '#F2D35E' },
  shareAutoTimerLabel: { color: '#8A6A00', fontWeight: '700', marginBottom: 4 },
  shareAutoTimerValue: { fontSize: 42, fontWeight: '900', color: '#D89B00' },
  shareAutoTimerHint: { color: '#7A5C00', marginTop: 6, fontWeight: '600' },
  shareAutoSetupHint: { color: '#8A6A00', marginTop: 8, fontSize: 12, fontWeight: '700' },
  shareAutoFoundHint: { color: '#6B4E00', marginTop: 8, fontSize: 13, fontWeight: '900' },
  shareAutoSorryText: { color: '#A43412', marginTop: 8, fontSize: 13, fontWeight: '800' },
  shareAutoDotsRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  shareAutoDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#D89B00', marginHorizontal: 6 },
  shareAutoGameBtn: { backgroundColor: '#0F8A47', paddingVertical: 12, paddingHorizontal: 18, borderRadius: 14, marginBottom: 10 },
  shareAutoGameBtnText: { color: 'white', fontWeight: '800' },
  shareAutoCancelBtn: { backgroundColor: '#1F2937', paddingVertical: 14, paddingHorizontal: 22, borderRadius: 16 },
  shareAutoCancelText: { color: '#FFF', fontWeight: '800' }
  ,gameWrap: { flex: 1, backgroundColor: '#FEF8E7', padding: 18 },
  gameHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 40, marginBottom: 10 },
  gameTitle: { fontSize: 24, fontWeight: '900', color: '#4B3B00' },
  gameClose: { color: '#0F8A47', fontWeight: '800' },
  gameMeta: { color: '#6B4E00', fontWeight: '800', marginBottom: 8 },
  gameHint: { color: '#7A5C00', marginBottom: 10 },
  gamePauseHint: { color: '#A43412', marginBottom: 10, fontWeight: '700' },
  gameArena: { flex: 1, backgroundColor: '#d5c4ff', borderWidth: 1, borderColor: '#E8C549', borderRadius: 18, marginTop: 12, position: 'relative', overflow: 'hidden' },
  gameFloatingTarget: { position: 'absolute', transform: [{ translateX: -18 }, { translateY: -18 }], width: 52, height: 52, borderRadius: 26, backgroundColor: '#FFD84D', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#B88900' },
  gameZombieTarget: { backgroundColor: '#FFD6D6', borderColor: '#A43412' },
  gameTargetText: { fontSize: 28 },
  profileScreenWrap: { flex: 1, backgroundColor: '#F3F7FC' },
  profileScreenHeader: { paddingTop: 56, paddingHorizontal: 18, paddingBottom: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  profileScreenTitle: { color: '#0F172A', fontWeight: '900', fontSize: 21, letterSpacing: 0.2 },
  profileScreenClose: { color: '#334155', fontWeight: '800', backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#D6DEFF', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999 },
  profileScreenContent: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 128 },
  profileCard: { backgroundColor: '#FFFFFF', borderRadius: 18, borderWidth: 1, borderColor: '#E2E8F0', padding: 15, marginBottom: 12, shadowColor: '#0F172A', shadowOpacity: 0.06, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  profileCardTitle: { color: '#0F172A', fontWeight: '900', marginBottom: 9, fontSize: 15, letterSpacing: 0.2 },
  profileLabel: { color: '#475569', fontWeight: '800', marginBottom: 6, fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.4 },
  profileInput: { backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 11, color: '#0F172A' },
  profileValue: { color: '#0F172A', fontWeight: '600', fontSize: 14, lineHeight: 20 },
  profileWalletValue: { color: '#0F766E', fontSize: 26, fontWeight: '900', letterSpacing: 0.2 },
  profileHistoryMeta: { color: '#0F766E', marginBottom: 8, fontWeight: '700', fontSize: 13 },
  profileHistoryRow: { backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, padding: 11, marginBottom: 8 },
  profileHistoryRoute: { color: '#1E293B', fontWeight: '700', fontSize: 13 },
  profileHistoryStatus: { color: '#64748B', marginTop: 3, fontSize: 12 },
  goHomeVehiclePageWrap: { flex: 1, backgroundColor: '#F8FAFC' },
  goHomeVehicleHeader: { paddingTop: 54, paddingHorizontal: 16, paddingBottom: 14, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E2E8F0', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  goHomeVehicleTitle: { fontSize: 22, fontWeight: '900', color: '#0F172A' },
  goHomeVehicleClose: { color: '#334155', fontWeight: '700' },
  goHomeVehicleBody: { padding: 16, flex: 1 },
  goHomeVehicleSub: { color: '#475569', marginBottom: 4, fontWeight: '700' },
  goHomeVehicleRoute: { color: '#0F172A', marginBottom: 14, fontWeight: '700' },
  goHomeVehicleGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  goHomeVehicleCard: { flex: 1, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 14, paddingVertical: 16, alignItems: 'center' },
  goHomeVehicleIcon: { fontSize: 30, marginBottom: 6 },
  goHomeVehicleName: { color: '#1E293B', fontWeight: '800' },
  goHomeVehicleFare: { color: '#0F766E', fontWeight: '800', marginTop: 2 },
  rideGameWrap: { flex: 1, backgroundColor: '#0B3A5B' },
  rideGameHeader: { paddingTop: 52, paddingHorizontal: 14, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#0C4A6E' },
  rideGameHeaderBtn: { color: '#E0F2FE', fontWeight: '800' },
  rideGameTitle: { color: '#F8FAFC', fontSize: 19, fontWeight: '900' },
  rideCongratsCard: { margin: 14, backgroundColor: '#ECFEFF', borderRadius: 18, borderWidth: 1, borderColor: '#67E8F9', padding: 14, alignItems: 'center' },
  rideCongratsTitle: { color: '#0C4A6E', fontWeight: '900', fontSize: 22 },
  rideCongratsSub: { color: '#155E75', marginTop: 4, textAlign: 'center', fontWeight: '700' },
  rideSparkle: { fontSize: 28, marginTop: 6 },
  rideTrackCard: { marginHorizontal: 14, backgroundColor: '#F8FAFC', borderRadius: 18, borderWidth: 1, borderColor: '#CBD5E1', padding: 14 },
  rideTrackLabel: { color: '#0F172A', fontWeight: '800' },
  rideProgressBarBg: { marginTop: 8, height: 12, backgroundColor: '#DBEAFE', borderRadius: 999, overflow: 'hidden' },
  rideProgressBarFill: { height: '100%', backgroundColor: '#2563EB' },
  rideTrackMeta: { marginTop: 8, color: '#475569', fontWeight: '700' },
  rideRoadArea: { marginTop: 12, height: 130, backgroundColor: '#111827', borderRadius: 14, position: 'relative', overflow: 'hidden' },
  rideRoadStripe: { position: 'absolute', top: 0, bottom: 0, left: '50%', width: 4, marginLeft: -2, backgroundColor: '#FCD34D' },
  rideAutoIcon: { position: 'absolute', bottom: 10, marginLeft: -16, fontSize: 34 },
  rideControlRow: { flexDirection: 'row', gap: 10, marginTop: 10 },
  rideControlBtn: { flex: 1, backgroundColor: '#1E3A8A', borderRadius: 10, paddingVertical: 10, alignItems: 'center' },
  disabledControlBtn: { opacity: 0.35 },
  rideControlText: { color: '#FFFFFF', fontWeight: '800' },
  rideLivesText: { color: '#0F172A', fontWeight: '800', marginTop: 10 },
  rideGameHint: { color: '#334155', marginTop: 6, fontSize: 13 },
  rideObstacle: { position: 'absolute', width: 28, height: 28, borderRadius: 8, backgroundColor: '#EF4444', justifyContent: 'center', alignItems: 'center' },
  rideObstacleText: { fontSize: 16 },
  rideCrashText: { color: '#B91C1C', fontWeight: '800', marginTop: 10, textAlign: 'center' },
  rideFinishedText: { color: '#15803D', fontWeight: '800', marginTop: 10, textAlign: 'center' },
  rideGameBottomActions: { marginTop: 12, marginHorizontal: 14, paddingBottom: 20 },
  // EARNINGS PAGE STYLES
  earningsCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 12, padding: 12, marginBottom: 8 },
  earningsDate: { fontSize: 14, fontWeight: '700', color: '#1F2937' },
  earningsAmount: { fontSize: 16, fontWeight: '900', color: '#059669' },
  totalEarningsCard: { backgroundColor: '#F0FDF4', borderWidth: 2, borderColor: '#22C55E', borderRadius: 14, padding: 14, alignItems: 'center', marginTop: 10 },
  totalEarningsLabel: { fontSize: 13, fontWeight: '700', color: '#16A34A', marginBottom: 4 },
  totalEarningsAmount: { fontSize: 28, fontWeight: '900', color: '#16A34A' },
  // RATING STYLES
  ratingSubtitle: { fontSize: 14, color: '#6B7280', marginBottom: 16, textAlign: 'center', fontWeight: '600' },
  starsContainer: { flexDirection: 'row', justifyContent: 'center', gap: 10, marginBottom: 16, marginTop: 10 },
  starButton: { padding: 8 },
  star: { fontWeight: '900' },
  ratingHint: { fontSize: 12, color: '#9CA3AF', textAlign: 'center', marginBottom: 16, fontWeight: '600' },
  ratingButtonRow: { flexDirection: 'row', gap: 10, marginTop: 10 },
  ratingButton: { flex: 1, paddingVertical: 10, borderRadius: 8, alignItems: 'center' },
  ratingButtonText: { color: 'white', fontWeight: '700', fontSize: 14 }
});
